"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&oz5$e20+ljp^j+359)hp2=vlv)d)l7r3($qutiqwkc0#cjt%*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Seller',
    'Buyer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

alipay_public_key_string = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvD6qw6vv56SjVdyXINbT/4mcK2QSaSupaPn1zhKR68Kj7RxJ035M1ouPgUYa7LvcfqrcOiSqMbnnaAwsbGkXxejujDJhwhUIAcXK6dT/kqJtgpg6qvzhLPOdSMwDvPe7ez+aFIVarjuTYNK9USzSH42cEBZJjOOv3keEuSpI1MZuOfE3lPebvyZEwxbAJETtVDUYE+FkHbHhEn2Xd3iIVDceNTNBmjGdYvkZlFB9Q2kGPa83HajkLGSdEqJD2fQpkF2e5TidS4INLMvJNBr2frGnP7huJ7C1N5/MBoq4okgE9xquMkEuhEBsyhKXPk8st2WdUtWMhcLcJPNKN/nfhwIDAQAB
-----END PUBLIC KEY-----'''

alipay_private_key_string = '''-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAvD6qw6vv56SjVdyXINbT/4mcK2QSaSupaPn1zhKR68Kj7RxJ035M1ouPgUYa7LvcfqrcOiSqMbnnaAwsbGkXxejujDJhwhUIAcXK6dT/kqJtgpg6qvzhLPOdSMwDvPe7ez+aFIVarjuTYNK9USzSH42cEBZJjOOv3keEuSpI1MZuOfE3lPebvyZEwxbAJETtVDUYE+FkHbHhEn2Xd3iIVDceNTNBmjGdYvkZlFB9Q2kGPa83HajkLGSdEqJD2fQpkF2e5TidS4INLMvJNBr2frGnP7huJ7C1N5/MBoq4okgE9xquMkEuhEBsyhKXPk8st2WdUtWMhcLcJPNKN/nfhwIDAQABAoIBAB0GaJwdEbOc3hZqGd9VYIDBPhQurOwMcGWgTPdGQ7ufWllACF4U1lIqWKktHw+rc7cQLz7D0n4yVOzlG6Bnn+PDI6z4Q7yCM6baUYw2bGW2p74ALOOadDnTIkhMNLNZW04Io4BQg4fj5biDJe+zQn7c/dg5J4QSw1Y5nsxSKcKsxayTaMf5B9Z6D9hEPlnR/bi1S4bVygnOYdn+42C1pG5CZ5IW8fMWxc21iuUyFdHTZpSEKA0+ZPaBOZH4LXfhlNwsffxvAcNlttY9pgVfWTCiuJWZVo6maxyWgCtd7c8api5PpNtI5RRz9VqqiIwRpM2jqLTW4pqI8hmpEPYPgokCgYEA+PCxdgMPlX9npYoKNVALZ61008EWZovl4qftBHcJy889VX36GOowBs0FiUO/A9h1jeAKX3MVUfYRTmT0Zzt9NGcREB7xXHD+jg1387HGxp/p3z4iefG2eTd8qX/xIAthES7Ydz5/sn4J7ABpHR7/CrqAoTh6UkTIr4N4QYTXL2sCgYEAwZVTLaKUtKki9jYiIvVAZjG1I6oi9A3fQZ4mvqMTh81Iecmtvrbt7oh9hHCQyjXLdSAJzzHSxjM62665ZytLirBSAB7llfct/QiQtHkZEYu84dA8ssYAePqzRB88G/IEVR3Q5DaRXbDPoGoA8y2fNBG1Eca2v3/+ioDSJE+Co1UCgYEA2+O3zVccz9/vDJEnPTpMKLNVy6n2AHS4hgHw4Y3IcGfJdJfHb3SFIay9pCbcNihghgaNAwzjmzcwyD9yhzFMAhq8PrImXpJMt+t7th2lSFN+wLvgtjhlByOVER+7PKPwhL4NZR8mquKcHwOp1ZhIjhB5iG8b1Ul+v1HwymbtsKsCgYASAB6h6bJGMkwL9PCrq353gjvDuzhQ1VFjOp+DropMYGxS1swPJdduDMcPH6B3DRWEKJyA5bMhtvXMI60dyMrXdJnLZRQYI8nk83zxKymHliTUIpbiUMMOfNFajkT6nECG4aTg86oEukI0OmcoNZ/OKa9anc20dORoYJ4pvjL5mQKBgALrsZ1C7yATOH5slzlBAVYPi0gfGFKVKSowmyvZRA2SRsfVf4SxuzkQHumJoSmYuyDoKQ86JVgMlF8lroVXMnLhteVtZ1Y2C/Kct5AgmuX+ycXmu6/lx+gOrdxizbyEwHnbc5gmcmvv8SWM3ApSywj9rUTt1AlhSgJgT++ZwC2M
-----END RSA PRIVATE KEY-----'''
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# STATIC_ROOT = os.path.join(BASE_DIR,'static')
