# Generated by Django 2.1.8 on 2019-10-07 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_valid_code'),
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(blank=True, max_length=11, null=True)),
                ('goods_name', models.CharField(blank=True, max_length=32, null=True)),
                ('goods_price', models.FloatField(blank=True, null=True)),
                ('goods_price_data', models.DateField(auto_now=True)),
                ('goods_inven', models.IntegerField(blank=True, null=True)),
                ('goods_area', models.CharField(blank=True, max_length=32, null=True)),
                ('goods_expr', models.IntegerField(blank=True, null=True)),
                ('goods_status', models.IntegerField(default=1)),
                ('goods_photo', models.ImageField(default='image/defaule_img.jpg', upload_to='foreground/image')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32)),
                ('type_desc', models.TextField()),
                ('type_photo', models.ImageField(default='images/banner01.jpg', upload_to='foreground/images')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.GoodsType'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.User'),
        ),
    ]
